### PR TITLE
Remove v1 embedding, bump version

### LINKED ISSUE #78: Does not build for Android with Flutter 3.29.0
App will not build on flutter `3.29.0` due to using outdated plugin APIs:

```
flutter-radar\android\src\main\java\io\radar\flutter\RadarFlutterPlugin.java:42: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
flutter-radar\android\src\main\java\io\radar\flutter\RadarFlutterPlugin.java:43: error: cannot find symbol
import io.flutter.view.FlutterMain;
                      ^
  symbol:   class FlutterMain
  location: package io.flutter.view
flutter-radar\android\src\main\java\io\radar\flutter\RadarFlutterPlugin.java:66: error: cannot find symbol
import io.flutter.view.FlutterNativeView;
                      ^
  symbol:   class FlutterNativeView
  location: package io.flutter.view
flutter-radar\android\src\main\java\io\radar\flutter\RadarFlutterPlugin.java:120: error: cannot find symbol
    public static void registerWith(Registrar registrar) {
                                    ^
  symbol:   class Registrar
  location: class RadarFlutterPlugin
```

### PR DESCRIPTION
**Pull request by jt274**
- Fixes breaking change on Flutter 3.29.0
- Will close #78

### CODE REVIEW

**Comment by KennyHuRadar** [comment]
Thank you for creating this PR, I'll take a harder look at this as soon as I have some more time.
To facilitate the quick merging of this PR, could you reference the breaking change and also justify backwards compatibility along with "safety" of this change?
Thanks!

**Comment by jt274** [comment]
This has been deprecated I believe since flutter `1.22`. Here is some more relevant info:

https://docs.flutter.dev/release/breaking-changes/android-v1-embedding-create-deprecation
https://docs.google.com/document/d/1wKspwf6LQu6uo32uQ9NcukfiKhLL4ButV9cwpjeb8QI/edit?tab=t.0
https://github.com/flutter/flutter/pull/160890

I see no other specific mention of this in the `3.29.0` release notes, but the release broke many plugins due to this same issue. I'm not able to spend any time verifying backwards compatibility or safety, but this fix has worked for me.

https://docs.flutter.dev/release/breaking-changes/plugin-api-migration

**Comment by Jonny1987** [comment]
Can this be reviews please? I can't increase my flutter version until this is fixed

**Comment by jt274** [comment]
@Jonny1987 You can feel free to use my fork here until this is merged: https://github.com/jt274/flutter-radar/tree/flutter-plugin-interface

**Comment by KennyHuRadar** [comment]
@Jonny1987 I did not forget about this, I'm a little caught up in a few other priorities right not but rest assured this is on my radar and I will get to this as soon as I can.
Thank you for your patience!

**Comment by KennyHuRadar** [comment]
Closing as https://github.com/radarlabs/flutter-radar/pull/82/files is merged into main
