### ISSUE TITLE
Does not build for Android with Flutter 3.29.0

### ISSUE THREAD

**Issue by jt274** [radarlabs/flutter-radar#78]
App will not build on flutter `3.29.0` due to using outdated plugin APIs:

```
flutter-radar\android\src\main\java\io\radar\flutter\RadarFlutterPlugin.java:42: error: cannot find symbol
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
  symbol:   class Registrar
  location: interface PluginRegistry
flutter-radar\android\src\main\java\io\radar\flutter\RadarFlutterPlugin.java:43: error: cannot find symbol
import io.flutter.view.FlutterMain;
                      ^
  symbol:   class FlutterMain
  location: package io.flutter.view
flutter-radar\android\src\main\java\io\radar\flutter\RadarFlutterPlugin.java:66: error: cannot find symbol
import io.flutter.view.FlutterNativeView;
                      ^
  symbol:   class FlutterNativeView
  location: package io.flutter.view
flutter-radar\android\src\main\java\io\radar\flutter\RadarFlutterPlugin.java:120: error: cannot find symbol
    public static void registerWith(Registrar registrar) {
                                    ^
  symbol:   class Registrar
  location: class RadarFlutterPlugin
```

**Comment by ConnorDykes** [comment]
Also new flutter projects in android to not have a n Application.kt with an onCreate method so the documentation for Android set up might not be correct anymore

**Comment by jt274** [comment]
I fixed in the PR above, just needs to be merged @KennyHuRadar

**Comment by jt274** [comment]
Closing since this fix was released.
